### PR TITLE
Make SSH key Vault path robust to different secret engines/versions

### PR DESCRIPTION
**Pull request by giorgiosironi**
Due to the use of the versioned key value secret store

### CODE REVIEW

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/data-pipeline-bigquery-views/blob/develop/Jenkinsfile.prod#L20 should be unaffected because this is only happening when using `-format=json`:
```
$ VAULT_ADDR=https://master-server.elifesciences.org:8200 vault kv get -field credentials secre
t/containers/data-pipeline/gcp                                                                                                                                             
{
  "type": "service_account",
  "project_id": "elife-data-pipeline",
  ...
}
```

**Review by de-code — APPROVED** [review]
seems to make sense. are we using it wrong with the json format option? doesn't seem that stable.

**Comment by giorgiosironi** [comment]
It was technically a new "major version" of this secret engine, but I'll compare with the non-JSON output. The advantage could be that we would support [other secret engines](https://www.vaultproject.io/docs/secrets/) too.

**Comment by giorgiosironi** [comment]
This looks good:
```
$ VAULT_ADDR=https://master-server.elifesciences.org:8200 vault kv get -field private_key secret/containers/ssh
-----BEGIN RSA PRIVATE KEY-----
...
```

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/process/job/process-ec2-plugin-ami-update/36/ is updating the nodes (recreating all of them).

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/view/data-pipeline/job/prod-data-pipeline-bigquery-views/32/console should be using this change.

**Pull request merged**
