### PR TITLE
Add kubectl and helm

### PR DESCRIPTION
**Pull request by giorgiosironi**
For https://github.com/elifesciences/issues/issues/5294

Depends on https://github.com/elifesciences/builder-configuration/pull/104

### CODE REVIEW

**Comment by tayowonibi** [comment]
> Depends on [elifesciences/builder-configuration#104](https://github.com/elifesciences/builder-configuration/pull/104)

https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fdata-hub-airflow-image/detail/PR-4/30/pipeline which is caused by  https://github.com/elifesciences/data-hub-airflow-image/blob/deploy_image_on_k8s/Jenkinsfile#L15

**Comment by giorgiosironi** [comment]
https://console.aws.amazon.com/iam/home?region=us-east-1#/users/containers didn't have enough permissions to access the EKS API, adding and re-running.

**Comment by giorgiosironi** [comment]
Not too bad now:
```
fetch from s3: fetch object from s3: AccessDenied: Access Denied
[2020-01-07T16:56:02.856Z] [54.224.139.67] out:                   	status code: 403, request id: CDA9DE7C729124EE, host id: LteP6GJV1dZf33i6DWgTjyEyluZBX+8Gm5Q56Ny1LMM+3f+oHCi7GGihojfSp9fay3On+ZO9QCM=
[2020-01-07T16:56:02.856Z] [54.224.139.67] out:                   Error: Looks like "s3://prod-elife-alfred/helm-charts" is not a valid chart repository or cannot be reached: plugin "bin/helms3" exited with error
```
Expanding permissions.

**Comment by giorgiosironi** [comment]
Added https://console.aws.amazon.com/iam/home?region=us-east-1#/policies/arn:aws:iam::512686554592:policy/AmazonS3AlfredBucketFullAccess to `containers`.

**Comment by giorgiosironi** [comment]
Further problems may appear when we actually use `helm` commands, but so far everything we can test in the formula execution with real AWS credentials and calls seems green.

**Pull request merged**
